### ISSUE TITLE
enable_node_group_private_networking causes initial cluster creation to fail

### ISSUE THREAD

**Issue by addisonj** [streamnative/terraform-aws-cloud#56]
The new default of enabling private networking causes the following error:

```
╷
│ Error: Invalid for_each argument
│ 
│   on .terraform/modules/sn_cluster.eks/main.tf line 103, in resource "aws_security_group_rule" "cluster_private_access_cidrs_source":
│  103:   for_each = var.create_eks && var.cluster_create_endpoint_private_access_sg_rule && var.cluster_endpoint_private_access && var.cluster_endpoint_private_access_cidrs != null ? toset(var.cluster_endpoint_private_access_cidrs) : []
│     ├────────────────
│     │ var.cluster_create_endpoint_private_access_sg_rule is true
│     │ var.cluster_endpoint_private_access is true
│     │ var.cluster_endpoint_private_access_cidrs is list of string with 3 elements
│     │ var.create_eks is true
│ 
│ The "for_each" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around this, use the
│ -target argument to first apply only the resources that the for_each depends on.

```

This can be worked around by disabling `enable_node_group_private_networking`, applying, and then re-enabling

**Comment by jrsdav** [comment]
The other [noted workaround](https://github.com/streamnative/terraform-aws-cloud/blob/77acda89b8692c24d11efbf920ef48ab5f173f47/examples/streamnative-platform/main.tf#L70) here is when composing the `vpc` module within the parent (as is the common pattern), we do a targeted apply of the VPC resource first to create the subnets that the [downstream resource](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/e90c877a741ab3cc4215376a70f7bcc360b6a3d2/main.tf#L103) is complaining about:

```shell
terraform apply --target module.vpc
```

Then proceed with:

```shell
terraform apply
```
