### ISSUE TITLE
Install metrics-server for eks clsuter 

### ISSUE THREAD

**Issue by nlu90** [streamnative/terraform-aws-cloud#75]
Our EKS cluster doesn't expose CPU/memory metrics (see below screenshot). 
Based on the link [here](https://docs.aws.amazon.com/eks/latest/userguide/metrics-server.html), we need to manually install metrics-server during cluster bootstrap for EKS clusters.

<img width="898" alt="image" src="https://user-images.githubusercontent.com/16407807/173702408-e37c3477-a336-4fd2-9089-8b55396c5fe8.png">

**Comment by polyzos** [comment]
yeah had the same thought as well. I'm installing the metrics server myself every time and I was thinking we should integrate it directly into the modules.

**Comment by jrsdav** [comment]
The metrics-server component has been added in by default in release [v2.3.0-alpha](https://github.com/streamnative/terraform-aws-cloud/releases/tag/v2.3.0-alpha).
