### ISSUE TITLE
Migrate to multiple node groups, one per each zone

### ISSUE THREAD

**Issue by addisonj** [streamnative/terraform-aws-cloud#8]
From the AWS docs here: https://docs.aws.amazon.com/eks/latest/userguide/cluster-autoscaler.html

AWS reccomends:

> Scope node groups across more than one Availability Zone
>
> We recommend that you configure multiple node groups, scope each group to a single Availability Zone, and enable the --balance-similar-node-groups feature. If you only create one node group, scope that node group to span over more than one Availability Zone.

We should migrate to multiple node groups, one per AZ

**Comment by jrsdav** [comment]
I believe this is already happening when we set the values for the `cluster-autoscaler` helm chart? 
https://github.com/streamnative/terraform-aws-cloud/blob/b9183cf6a1db3e873aba3439ea32a8d8b70d2bae/cluster_autoscaler.tf#L120
