### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by bobcorsaro** [streamnative/terraform-aws-cloud#82]
https://github.com/streamnative/terraform-aws-cloud/blob/661fd3a689158fe044d2647340c3f155b257b40c/modules/managed-cloud/variables.tf#L20

`s/policiy/policy/`

**Comment by jrsdav** [comment]
Resolved in release https://github.com/streamnative/terraform-aws-cloud/releases/tag/v2.3.2-alpha
