### ISSUE TITLE
Ensure node-groups have encrypted root volumes

### ISSUE THREAD

**Issue by addisonj** [streamnative/terraform-aws-cloud#9]
We should default our node-groups to use encrypted  root  volumes.

This will better comply with our security policies of encryption by default

**Comment by jrsdav** [comment]
Looks like they added support for this through a launch config. 
https://github.com/aws/containers-roadmap/issues/585#issuecomment-675093297

I'll dig into the parent EKS module we're using to see how I create and pass one to the `node_groups` sub module. 
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/modules/node_groups/launch_template.tf

**Comment by jrsdav** [comment]
Example of enabling it in the module:
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/9022013844a61193a2f8764311fb679747807f5c/examples/launch_templates_with_managed_node_groups/launchtemplate.tf#L32
