### ISSUE TITLE
Add domain-filter and --txt-owner-id to external-dns

### ISSUE THREAD

**Issue by addisonj** [streamnative/terraform-aws-cloud#92]
External-dns, without a domain-filter, we query all route53 zones for record changes.

This can cause a large amount of r53 traffic.

All instances of external-dns should be run with a domain-filter to reduce the number of domains it queries across.

**Comment by EronWright** [comment]
That's a good idea. 

While we're checking the external-dns configuration (`--domain-filter`), may I suggest that we ensure that `--txt-owner-id` is also configured to the name of the pool member, at least for new deployments.  This allows for two pool members to use the same domain without clashing.  Honestly I believe that each pool member should have a separate domain, and this might be a non-issue.

**Comment by gengmao** [comment]
this is a corrective action of https://github.com/streamnative/production/issues/189

**Comment by jrsdav** [comment]
This has been added in the `external-dns` configuration for the upcoming release of the refactored module ([ref](https://github.com/streamnative/terraform-aws-cloud/pull/91/commits/aaf78fbb6c9c59af2969b083f58d50ffe95e2189)).
